Repository BochilGaming/games-wabot, pull requests merged in 2021-09, with the labels that each got.

#76 Fix sticker?
  lib/sticker.js
  nodemon.json
  package.json
  plugins/sticker.js
  test2.js
Labels: enhancement, FIX

#64 Update creator.js
  config.js
  handler.js
  lib/simple.js
  main.js
  plugins/creator.js
  plugins/join.js
  plugins/request.js
Labels: enhancement

#78 dddddeploy to heeeroku?
  README.md
  app.json
Labels: documentation, enhancement
